<#
install / uninstall round-trips on COPIES of settings.json (never the real one):
  uninstall(install(x)) == x byte for byte, reinstall is idempotent, and only pokeshell profiles change.
  powershell -NoProfile -File tests\test-install.ps1 [-Settings <a settings.json to copy>]
#>
param([string]$Settings)
. (Join-Path $PSScriptRoot '_setup.ps1')
. (Join-Path $RepoRoot 'scripts\lib\wtsettings.ps1')
$work = Join-Path ([IO.Path]::GetTempPath()) "pokeshell-test-install-$PID"
Remove-Item $work -Recurse -Force -ErrorAction SilentlyContinue
[void][IO.Directory]::CreateDirectory($work)
$real = Get-PokeshellWtSettingsPath
$realHash = if ($real) { (Get-FileHash $real).Hash }
$skinCount = @(Get-PokeshellSkins $RepoRoot | Where-Object { Test-Path $_.shader }).Count

function Invoke-Cli([string]$State, [string[]]$CliArgs) {
  $env:POKESHELL_HOME = $State
  try { & powershell.exe -NoProfile -ExecutionPolicy Bypass -File (Join-Path $RepoRoot 'scripts\pokeshell.ps1') @CliArgs 2>&1 | Out-String }
  finally { Remove-Item Env:POKESHELL_HOME }
}

$cases = [ordered]@{}
if (-not $Settings) { $Settings = $real }
if ($Settings -and (Test-Path $Settings)) {
  # pokeshell may already be installed there: start the round trip from the copy without its profiles
  $s = Read-WtSettingsFile $Settings
  $bytes = [Text.UTF8Encoding]::new($false).GetBytes((Remove-PokeshellProfilesText $s.text @()))
  if ($s.bom) { $bytes = [byte[]](0xEF, 0xBB, 0xBF) + $bytes }
  $cases['your settings.json (copy, pokeshell profiles removed)'] = [byte[]]$bytes
}
$utf8 = [Text.UTF8Encoding]::new($false)
$cases['comments + trailing commas + CRLF'] = $utf8.GetBytes((@'
// This file was initially generated by Windows Terminal
{
    "$schema": "https://aka.ms/terminal-profiles-schema",
    "defaultProfile": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}", // plain PowerShell
    /* block
       comment */
    "profiles": {
        "defaults": { "font": { "face": "Cascadia Mono", "size": 11.5 } },
        "list": [
            { "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}", "name": "Windows PowerShell", "commandline": "powershell.exe \"x\\y\"", "hidden": false },
            // cmd
            { "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}", "name": "Command Prompt ünïcödé", "hidden": false, },
        ]
    },
    "schemes": [], "actions": [ { "command": "paste", "keys": "ctrl+v" } ],
}
'@).Replace("`r`n", "`n").Replace("`n", "`r`n"))
$cases['BOM + LF + 2-space indent'] = [byte[]](0xEF, 0xBB, 0xBF) + $utf8.GetBytes((@'
{
  "profiles": {
    "list": [
      {
        "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
        "name": "Windows PowerShell"
      }
    ]
  }
}
'@).Replace("`r`n", "`n"))
$cases['legacy bare profiles array, one line'] = $utf8.GetBytes('{"profiles":[{"guid":"{61c54bbd-c2c6-5271-96e7-009a87ff44bf}","name":"Windows PowerShell"}],"schemes":[]}')

$i = 0
foreach ($name in $cases.Keys) {
  $i++
  Write-Host "$i. $name" -ForegroundColor Cyan
  $file = Join-Path $work "settings$i.json"; $state = Join-Path $work "state$i"
  [IO.File]::WriteAllBytes($file, $cases[$name])
  $orig = [IO.File]::ReadAllBytes($file)
  $out = Invoke-Cli $state @('install', '-SettingsPath', $file)
  $after1 = [IO.File]::ReadAllBytes($file)
  $text = (Read-WtSettingsFile $file).text
  $items = @((Get-WtProfileList (ConvertFrom-Jsonc $text)).items)
  $ours = @($items | Where-Object { Test-PokeshellProfileNode $_ @() })
  Assert ($ours.Count -eq $skinCount) "install added $($ours.Count) hidden skin profiles (expected $skinCount)"
  Assert ($items.Count -eq $ours.Count + @((Get-WtProfileList (ConvertFrom-Jsonc (Read-WtSettingsFile $file).text)).items | Where-Object { -not (Test-PokeshellProfileNode $_ @()) }).Count) "the other profiles are still there"
  $bomBefore = $orig.Length -ge 3 -and $orig[0] -eq 0xEF; $bomAfter = $after1.Length -ge 3 -and $after1[0] -eq 0xEF
  Assert ($bomBefore -eq $bomAfter) "byte-order mark preserved ($bomBefore)"
  Assert (@(Get-ChildItem (Join-Path $state 'backups') -Filter *.json).Count -ge 1) "backup written before editing"
  Assert ($out -match [regex]::Escape('scripts\pokeshell-profile.ps1')) "prints the `$PROFILE line"
  $null = Invoke-Cli $state @('install', '-SettingsPath', $file)
  Assert ([Convert]::ToBase64String([IO.File]::ReadAllBytes($file)) -eq [Convert]::ToBase64String($after1)) "re-install is idempotent"
  $null = Invoke-Cli $state @('uninstall', '-SettingsPath', $file)
  Assert ([Convert]::ToBase64String([IO.File]::ReadAllBytes($file)) -eq [Convert]::ToBase64String($orig)) "uninstall restores the original byte for byte"
  Assert (-not (Test-Path (Join-Path $state 'installed.tsv'))) "uninstall forgets the installed skins"
}

Write-Host "$($i + 1). a pokeshell profile first in the list, then other profiles" -ForegroundColor Cyan
$t = '{"profiles":{"list":[{"guid":"{a}","name":"pokeshell: x/y"},{"guid":"{b}","name":"B"},{"guid":"{c}","name":"pokeshell: x/z"},{"guid":"{d}","name":"D"}]}}'
$clean = Remove-PokeshellProfilesText $t @()
Assert ($clean -eq '{"profiles":{"list":[{"guid":"{b}","name":"B"},{"guid":"{d}","name":"D"}]}}') "leading + middle removal: $clean"
Assert ((Remove-PokeshellProfilesText '{"profiles":{"list":[{"name":"pokeshell: a"}]}}' @()) -eq '{"profiles":{"list":[]}}') "removing every profile keeps the brackets"

if ($real) { Assert ((Get-FileHash $real).Hash -eq $realHash) "the real Windows Terminal settings.json was not touched" }
Remove-Item $work -Recurse -Force -ErrorAction SilentlyContinue
Write-Host ''
if ($script:Failures) { Write-Host "install: $script:Failures FAILED" -ForegroundColor Red; exit 1 }
Write-Host "install: all passed" -ForegroundColor Green
